btrfs: add extra error handling for btrfs_init_new_device()
With all the new error handling for super block writebacks, now a tiny
device add will fail as expected:

 # lsblk  /dev/loop0
 NAME  MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
 loop0   7:0    0  64K  0 loop
 # mount /dev/test/scratch1  /mnt/btrfs/
 # btrfs device add -f /dev/loop0 /mnt/btrfs/
 Performing full device TRIM /dev/loop0 (64.00KiB) ...
 ERROR: error adding device '/dev/loop0': Input/output error

And the on-disk super block is still pointing to the older chunk tree:

 # btrfs ins dump-tree -t chunk /dev/test/scratch1
 ...
         item 0 key (DEV_ITEMS DEV_ITEM 1) itemoff 16185 itemsize 98
                devid 1 total_bytes 10737418240 bytes_used 562036736
                io_align 4096 io_width 4096 sector_size 4096 type 0
                generation 0 start_offset 0 dev_group 0
                seek_speed 0 bandwidth 0
                uuid 87358ef3-2cd2-4a4c-b607-4cba0cc80a3b
                fsid 26f7058c-2604-4293-a580-6efc653b849d
        item 1 key (FIRST_CHUNK_TREE CHUNK_ITEM 13631488) itemoff 16105 itemsize 80

But after the above error, we still can not properly mount the original
fs again:

 # umount /mnt/btrfs
 # mount /dev/test/scratch1 /mnt/btrfs
 mount: /mnt/btrfs: can't read superblock on /dev/mapper/test-scratch1.
       dmesg(1) may have more information after failed mount system call.
 # dmesg -t | tail -n 3
 BTRFS info (device dm-2): using crc32c (crc32c-lib) checksum algorithm
 BTRFS error (device dm-2): failed to read devices
 BTRFS error (device dm-2): open_ctree failed: -5

The mount failure is caused by the missing error handling of the
btrfs_commit_transaction() inside btrfs_init_new_device().

If that call failed, we should remove the new device, or it will pollute
the fs_devices, causing newer mounts to fail until the device is
forgotten manually.

Signed-off-by: Qu Wenruo <wqu@suse.com>